.PHONY: check
check: ## check
	@go generate ./...
	@go fmt ./...
	@go vet ./...
	@go install ./...

.PHONY: help
help:	## show this help
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'